apiVersion: v1
kind: Pod
metadata:
    labels:
        podname: testpod
spec:
    containers:
    - name: kubectl
      image: docker.io/bitnami/kubectl:latest
      command:
      - cat
      tty: true
    serviceAccount: jenkins
